PACKAGE = infonet.javasim.bgp4.comm

SOURCE  = \
		BGPMessage.java \
		BGPMessageConstants.java \
		BGPSerializable.java \
		KeepAliveMessage.java \
		NotificationMessage.java \
		OpenMessage.java \
		StartStopMessage.java \
		TransportMessage.java \
		UpdateMessage.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
