PACKAGE = infonet.javasim.FT

SOURCE  = \
		FT.java \
		FTEntry.java \
		FTInetConstants.java \
		FTKey.java \
		IPRadixTree.java \
		OutLabel.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
