PACKAGE = infonet.javasim.bgp4.timing

SOURCE  = \
		EventTimer.java \
		MRAIPerPeerTimer.java \
		MRAITimer.java \
		TimeoutMessage.java \
		TimerConstants.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
