PACKAGE = infonet.javasim.bgp4.policy

SOURCE  = \
		Action.java \
		AtomicAction.java \
		AtomicPredicate.java \
		Clause.java \
		Predicate.java \
		RouteMap.java \
		Rule.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
