PACKAGE = infonet.javasim.bgp4

SOURCE  = \
		AdjRIBIn.java \
		AdjRIBOut.java \
		BGPSession.java \
		BGPSessionConstants.java \
		Debug.java \
		Global.java \
		InBuffer.java \
		LocRIB.java \
		PeerConnection.java \
		PeerConnectionConstants.java \
		PeerEntry.java \
		RIBElement.java \
		Route.java \
		RouteInfo.java \
		TwoLevelInBuffer.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
