PACKAGE = infonet.javasim.bgp4.path

SOURCE  = \
		Aggregator.java \
		ASpath.java \
		AtomicAggregate.java \
		Attribute.java \
		ClusterList.java \
		Community.java \
		ExtendedCommunities.java \
		ExtendedCommunity.java \
		LocalPref.java \
		MED.java \
		NextHop.java \
		Origin.java \
		OriginatorID.java \
		RedistributionCommunity.java \
		Segment.java \
		TBID.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
